### ISSUE TITLE
[Value Card - data-state-error] Tooltip openend after clicking no data or error icon opens behind other Tiles/cards

### ISSUE THREAD

**Issue by agupta2-ibm-maximo** [IBM/carbon-addons-iot-react#1040]
[Value Card - data-state-error] Tooltip openend after clicking no data or error icon opens behind other Tiles/cards

GRAPHITE team has implemented the data-state-error value cards in Reference application Dashboard. Since it has multiple tiles/cards on the page. here if we are clicking on the no data or error icon the tooltip is opening behind other cards. As per discussion with team, they are mentioning that they are not directly using the IOT component and not modifying tooltip in GRAPHITE hence it seems to be fixed in IOT,

The other issue is that if the card is very near to left or right edge of browser, tooltip positioning is such that some part of the tooltip is not completely visible.

Please help in fixing these tooltip issues.

**Comment by agupta2-ibm-maximo** [comment]
![Chrome-Resize-Error state tile Tooltip issue](https://user-images.githubusercontent.com/56728062/77543021-0df91480-6ecd-11ea-8615-c3a4dae61c05.jpg)
![Screenshot_20200325_125534_com android chrome](https://user-images.githubusercontent.com/56728062/77543040-13eef580-6ecd-11ea-82c9-a0ffe7557023.jpg)

Please see these attachments.

**Comment by bjornalm** [comment]
I will create a PR with a fix for the z-index issue so that the tooltip doesn't open behind other cards.

@lukefirth @davidicus 
For the tooltip alignment there is no quick fix available as far as I know, it is a known problem for the carbon based tooltip in general. 

A possible short-term workaround could be to center the icon so that it is further away from the edge. This should only be done for Card sizes that are hiding additional data-state texts i.e. SMALL, SMALLWIDE and MEDIUMTHIN. 
![image](https://user-images.githubusercontent.com/5167091/77559979-1e08f800-6ebd-11ea-9721-11ebf4a45ec5.png)

For the other card sizes there is also a data-state title and description that the user can click to have the tooltip appear in the middle of the card.

The CSS to center the icon would be:

```
.iot--data-state-grid {
    grid-template-columns: 1fr auto auto;
}

.iot--data-state-grid > *:first-child {
    margin-left: auto;
    margin-right: auto;
}
```

**Comment by stuckless** [comment]
I wonder if this is going to be an ongoing battle with tooltips :(  It is why I like the idea of allowing something else to be in charge of rendering the tooltip, since we had to do a huge amount of work to get tooltips rendering correctly when in dialogs, flyouts, etc. and manage the positioning of tooltips relative to the screen, etc.

**Comment by bjornalm** [comment]
@stuckless Is the code for your tooltip available somewhere for us to look at?
