### ISSUE TITLE
[Card,PageTileBar] Invalid Prop Types

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#1120]
[Internal Watson-IoT/pal-tracking#385](https://github.ibm.com/Watson-IoT/pal-tracking/issues/385)

I have these changes done locally but I could not actually create the PR from a clean install because it kept failing on storyshot snapshot tests.  So, here's the changes, they are small.

In Card, `showOverflow` has been deprecated, but, it's also in the default props.  This means you see the deprecation message always even if you are not using the prop.

In PageTitleBar.jsx it is using `PropTypes.oneOf()` incorrectly.  `oneOf` expects and array, but this is passing each type an arg, not in an array.

**Comment by tay1orjones** [comment]
- ShowOverflow was previously a required prop, and so was required to have a default prop. Since it was deprecated, we can remove it from default props [here](https://github.com/IBM/carbon-addons-iot-react/blob/c017656dc03532fe6ea23108c0374c60008aab58/src/components/Card/Card.jsx#L138).
- I think the PageTitleBar prop you're referring to is `description`. It was recently changed [in this commit](https://github.com/IBM/carbon-addons-iot-react/commit/cec9c0b5336d5aa39f8a89a239974ad0e4f321ef). It looks like it should be using `oneOfType` instead of `oneOf`, but @davidicus can confirm.
