### ISSUE TITLE
[Table]: Twisty Can we set  icon indicators to the far left of the twisty and or selection checkbox

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#123]

**Comment by matsgothe** [comment]
This request covers a general need to indicate state and progress related to a row. 
The visual design should be adaptive to the vertical scrolling and allocation space on left and right sides of the table row to show state, progress, and row actions, independent of the horizontal scroll.
The allocated space may be responsive to avoid unused space in common cases.
The allocated space should be restrictive to avoid unused space
The allocated space should not break vertical alignment.

**Comment by matsgothe** [comment]
Assigning to Amy for visual design

**Comment by matsgothe** [comment]
Assigning to Amy for visual design

**Comment by amymillett** [comment]
@scottdickerson 
In general, I would recommend against having special, independent indicators like these:
![Screen Shot 2019-04-08 at 1 23 52 PM](https://user-images.githubusercontent.com/48336859/55747333-9f901d80-5a01-11e9-9b53-91255e105eaf.png)![Screen Shot 2019-04-08 at 1 24 28 PM](https://user-images.githubusercontent.com/48336859/55747343-a7e85880-5a01-11e9-9a72-6589b63b865f.png)

I don't think it would be immediately obvious to a user what these circles indicate because they have no column header or text descriptor. It took me awhile to realize a red dot in IoTCS meant error and I would never have guessed could be clicked on to reveal an error message. 

Adding the connection status (or error status, progress status, ect) as a proper column makes it a little easier to understand with the added bonus of being filterable. Here's some examples, one of which I have proposed for the Platform tables:

![Screen Shot 2019-04-08 at 1 40 52 PM](https://user-images.githubusercontent.com/48336859/55748335-ff87c380-5a03-11e9-8dcd-3254bf75c7f4.png)


![Screen Shot 2019-04-08 at 1 40 40 PM](https://user-images.githubusercontent.com/48336859/55748328-fd256980-5a03-11e9-937c-8aef66ae428b.png)


![Screen Shot 2019-04-08 at 1 49 00 PM](https://user-images.githubusercontent.com/48336859/55748767-1aa70300-5a05-11e9-8da0-1a13d375bb6d.png)

**Comment by scottdickerson** [comment]
We've decided not to do this and instead follow @amymillett advice
