### ISSUE TITLE
[Table] cells will overflow under some conditions

### ISSUE THREAD

**Issue by stuckless** [IBM/carbon-addons-iot-react#1262]
### Describe the bug

![image](https://user-images.githubusercontent.com/1056553/83567423-90b2d700-a4ef-11ea-8ed5-d18156b33aac.png)

This is affecting the Health release in that they have many columns are overflowing in this way.

### To Reproduce
Basically set the table wdith to `undefined` (or a number), and on the column set to `wrap: never` and give it data that very wide.  It just overlows into the next cell.

```
  .add('Custom overflowing content', () => {
    const tableColumns = [
      {
        id: 'date',
        name: 'Date',
        width: undefined,
        renderDataFunction: ({ value: date }) => (
          <div>
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          </div>
        ),
      },
      {
        id: 'string',
        name: 'String',
        filter: { placeholderText: 'enter a string' },
      },

      {
        id: 'select',
        name: 'Select',
        filter: { placeholderText: 'pick an option', options: selectData },
      },
      {
        id: 'secretField',
        name: 'Secret Information',
      },
      {
        id: 'status',
        name: 'Status',
        renderDataFunction: renderStatusIcon,
        sortFunction: customColumnSort,
      },
      {
        id: 'number',
        name: 'Number',
        filter: { placeholderText: 'enter a number' },
      },
      {
        id: 'boolean',
        name: 'Boolean',
        filter: { placeholderText: 'true or false' },
      },
      {
        id: 'node',
        name: 'React Node',
      },
    ];

    return (
      <Table
        columns={tableColumns}
        options={{
          wrapCellText: 'auto',
        }}
        data={tableData}
        actions={actions}
        view={{
          filters: [
            { columnId: 'string', value: 'whiteboard' },
            { columnId: 'select', value: 'option-B' },
          ],
          toolbar: {
            activeBar: 'filter',
            customToolbarContent: (
              <StyledCustomToolbarContent>my custom</StyledCustomToolbarContent>
            ),
          },
        }}
      />
    );
  })
```

**Comment by bjornalm** [comment]
For a column with a very long text, fixed width like `100px` and the option `wrapCellText: 'never'` it actually it makes sense that we get overflow, but in the example I see that you use `wrapCellText: 'auto'` which should force the the text to be truncated. 

**However**, you are also using the `renderDataFunction` for that column and that function is more than just a string manipulation function and puts the app in charge of the cell rendering. This means that some "built in" functionality like the overflow is now the responsibility of the application. See the relevant code here:
https://github.com/IBM/carbon-addons-iot-react/blob/master/src/components/Table/TableBody/TableBodyRow/TableBodyRow.jsx#L425-L452

@stuckless, I remember you saying that you use the renderDataFunction to manipulate strings, and as I suggested then, I think that we should add a value preprocessor function to use here instead of the very powerful `renderDataFunction`. The output of that function can still be added to our normal TableCellRenderer and enjoy the same functionality as "normal" values.

**Comment by bjornalm** [comment]
Workaround for dealing with links:

JS
Add a class to your wrapper element, e.g. my-table-link

```
renderDataFunction: ({ value: date }) => (
  <div className="my-table-link">
    <a href="http://carbon-addons-iot-react.com/?path=/story/watson-iot-table--with-resize-and-initial-column-widths-on-simple-stateful-and-row-selection">
      http://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.something.com
    </a>
  </div>
),
```

CSS
The text-overflow mixin comes from Carbon
```
// Activated when wrapCellText=auto allows truncation
.iot--table__cell--truncate .my-table-link {
  @include text-overflow();
}
```

**Comment by bjornalm** [comment]
I agree to the argument from the slack thread that the table should probably never overflow like in this issue. We could add a fix to prevent this particular scenario, but the main problem persists when we let the application render anything in the cell, it becomes impossible to guarantee that it works like the built in cell rendering functionality.

E.g. we could wrap the renderDataFunction in a div and to that div we add something like:
```
white-space: nowrap;
overflow: hidden;
text-overflow: ellipsis;
```
if the table should allow truncation. But, that only works properly if the render function renders the link directly, and not in its own wrapping div. The overflow is still prevented, but we don't get the ellipsis.

**Comment by bjornalm** [comment]
@stuckless FYI, see PR
