### ISSUE TITLE
[FlyoutMenu] aka carbon modeless dialog

### ISSUE THREAD

**Issue by tay1orjones** [IBM/carbon-addons-iot-react#1266]
### Summary

This is a general purpose menu dialog, typically attached to an icon.
A modal dialog was not used because the user needs to be able to see the data in the table.

**Additional context**
[Internal Watson-IoT/pal-tracking#44](https://github.ibm.com/Watson-IoT/pal-tracking/issues/44)

@lukefirth could you provide the spec documents for this? Also is it pertinent to identify if this is in fact modeless? Is `FlyoutMenu` an appropriate title for this?

Will be similar to [what's available in Graphite](https://pages.github.ibm.com/maximo-app-framework/graphite/react/storybook/?path=/story/components-%E2%98%A2-flyout--flyoutcontroller-relative)

**Comment by tay1orjones** [comment]
From initial conversations it looks like this could be fairly similar to the interactive tooltip under the hood. We might be able to restyle the interactive tooltip under the `FlyoutMenu` component name.

**Comment by lukefirth** [comment]
OK, so I'm about to take this from 'there is some vague spec' to 'there's a lot of spec' status. Apologies that I was unable to engage until now.

Warning: These will be large images, because I want to share them faster with you, rather than spend forever packaging them and have everyone waiting longer. 

----

**A brief intro to the component, just to frame the way it should be thought about:** 
![Intro](https://user-images.githubusercontent.com/30671949/84955558-1cfef580-b0bd-11ea-91aa-7468752b9245.png)
- Note: Content size can be anything in theory, but I am recommending an upper limit that matches carbons XL modal width (960px)
- The footer area is 64px so that we need to place modal footers in there, we can. But it can also be used to house other content, such as regular buttons of varying styles.
-----

**Now, some more detailed spec. I've left some things relatively unsaid here, due to being referenced/tied to the carbon implementation of both the ghost button and the overflow menu that we should steal from**
![Spec](https://user-images.githubusercontent.com/30671949/84955684-53d50b80-b0bd-11ea-8d9b-434c381a5322.png)
- See the 'light' modifier details in the bottom right of this image.


-----

**Time now to talk about  its behavior based on where it is triggered from, in order to make it easier to consume in different viewport sizes**
![Trigger location logic](https://user-images.githubusercontent.com/30671949/84955982-e2e22380-b0bd-11ea-8188-895a69d41bee.png)
- @tay1orjones I would appreciate your notes here around our discussion of how to offer this capability.

-----

**What about problem scenarios with this? When things still don't fit?**
![Problem scenarios](https://user-images.githubusercontent.com/30671949/84956040-02794c00-b0be-11ea-9bca-95feaef2fcd6.png)


-----

**And finally, a grab bag of examples to give all this abstract talk some substance**
![Examples](https://user-images.githubusercontent.com/30671949/84956088-158c1c00-b0be-11ea-9d82-dd96687dc296.png)

**Comment by tay1orjones** [comment]
Thanks for the detailed info @lukefirth!

Currently #1306 is open with a WIP initial implementation that should contain the general functionality of open/close and manual/preconfigured positioning via application code. We're using the tooltip under the hood, so the prop signature is the exact same.

So I'd expect there we can deliver the visual spec you linked above. The broader more "smart" positioning should be lumped in with tooltip positioning improvements to come #802
