### ISSUE TITLE
[Table]: Visual design of 'clear all' filter button

### ISSUE THREAD

**Issue by matsgothe** [IBM/carbon-addons-iot-react#137]
The current visual design places the Clear All button to the upper right part of the table, next to table action buttons.

A proposal is to move the clear all to an action that is aligned with the filters the button will clear. For example to the left of the filters section. Or just as a (x) button with no text.

This link do not show this proposal, but show the Guidea desing of the clear all button.
https://ibm.box.com/s/ja1q949090559epejeocco8st3njgvgh

@amymillett to review

**Comment by amymillett** [comment]
@matsgothe I still don't quite understand this one. In the original design, the "clear all filters" button was to the left of the icons in the toolbar. 

<img width="670" alt="Screen Shot 2019-04-08 at 8 41 47 AM" src="https://user-images.githubusercontent.com/48336859/55728682-292bf500-59da-11e9-8130-f9ce05666faa.png">

The Guidea design has the "clear all filters" button to the right of the icons of the toolbar. I think they were saying not to do this because when the button appeared it would push the icons over. But it seems like they were the ones that created this problem in the first place.

<img width="353" alt="Screen Shot 2019-04-08 at 8 44 02 AM" src="https://user-images.githubusercontent.com/48336859/55728818-7b6d1600-59da-11e9-8aa2-b2198edf09f0.png">

I don't see this being something we need to change as long as the clear all filters button stays to the left of the icons in the toolbar. The filters still allow individual removal in each text field, but the clear all button is mostly for user convenience.

**Comment by matsgothe** [comment]
@amymillett yes, I'm fine with this and our current design with the button to the left of the standard table icons. (I  confirmed in the React storybook that the actions, buttons and icons stay fixed when the table scrolls horizontally).
