### ISSUE TITLE
[table] update the column picker for v10

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#331]
Column picker needs a visual update to align with the Carbon v10 upgrade.

Will be considered complete when:
- [x] Visual design is received from @amymillett and posted here
- [x] Visual design is implemented in the component.

**Comment by amymillett** [comment]
**4. Column reordering**

- This definitely needs some Carbon X-ing, since it's a custom feature
![Screen Shot 2019-06-24 at 1 50 42 PM](https://user-images.githubusercontent.com/48336859/60044045-29f23000-9687-11e9-85aa-c4c99efc1f8a.png)

- My suggestion involves changing the buttons to black, styled after the secondary button:
![Screen Shot 2019-06-24 at 2 05 47 PM](https://user-images.githubusercontent.com/48336859/60044982-3ecfc300-9689-11e9-921f-ef4fa3344d47.png)

- It's also worth noting that Guidea has recommended an entirely different design for column picking and reordering, but we do not have that implemented in any way (as far as I know)
![Screen Shot 2019-06-24 at 2 07 07 PM](https://user-images.githubusercontent.com/48336859/60045037-5eff8200-9689-11e9-9d69-ec13c5aa7f86.png)

**Comment by amymillett** [comment]
See more information regarding Carbon X table updates here: https://github.com/IBM/carbon-addons-iot-react/issues/339

**Comment by davidicus** [comment]
Closed with [this](https://github.com/IBM/carbon-addons-iot-react/pull/389) PR.
