### ISSUE TITLE
[Table] Table component doesn't have IDs on elements

### ISSUE THREAD

**Issue by camilasb** [IBM/carbon-addons-iot-react#409]
Steps:
1. Open the IoT Storybook
https://beta.carbon-addons-iot-react.com/?path=/story/table--stateful-example-with-expansion
2. Click on Table option on the left panel
3. Inspect the elements of the component

Actual Result: There are no IDs on the elements
Expected Result: IDs are crucial for test automation purposes. Using xpaths is too fragile.

**Comment by tay1orjones** [comment]
Thanks for bringing this up! I'm curious if you could provide some more context around the automated testing you're using. 

Most (all?) of the components support adding a `className`, which can be used in many automated testing frameworks to select elements.

IDs can be tricky in react and generally aren't recommended. That said, xpaths can be brittle, and I like the thoughts laid out in [the Cypress.io documentation on preferring selecting elements via `data-` attributes](https://docs.cypress.io/guides/references/best-practices.html#Selecting-Elements) instead of classes or IDs. 

We'd need to add support for these data attributes via props on existing components. Presently we don't pass any attributes down to the lower level dom elements.

**Comment by camilasb** [comment]
Hi! We basically have an automation framework selenium based and our standard is to use IDs to interact with the elements in the screen, since xpaths are too fragile and can mess up all our scripts if any div changes. I'm actually trying to grab the elements in this table component now and it's already kinda hard.
In our case, we do have a mechanism to give elements unique and fixed IDs so we don't need to rely on position of the elements in the screen to make our tests to work fine.
We will need this one day or another in the near future cause it's the way we follow our process in here, so I'm trying already to get rid of this "problem" beforehand =)
Do you think you guys can help us out?

**Comment by camilasb** [comment]
@tay1orjones do you have any news on this? =)

**Comment by tay1orjones** [comment]
For the components that we control, we can extend them to have [spread attributes](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes). Most of the underlying Carbon components support this, we should too.

Once we do this, you'll likely need to compose the components yourself to set the [specific props/attributes you require](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html). 

We can explore extending composed/stateful components as well, like `StatefulTable`. These may need to append values to id props you provide though. For example, `StatefulTable` already takes an `id` as a prop, it just doesn't surface this value in the DOM yet. Rows and cells then append another unique id to this prop for their own use.
