### ISSUE TITLE
[Table] scalability to millions of rows and up to 500 columns

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#458]
[Internal Watson-IoT/pal-tracking#409](https://github.ibm.com/Watson-IoT/pal-tracking/issues/409)

We need clarity on the specifics of this ask. From a UX standpoint, usability would dictate that we would never surface this many rows or columns to the user. 

Clarifications of the ask should be posted in the thread and any eventual ux design work should be added here to inform the development of this feature.

**Comment by tay1orjones** [comment]
@stuckless reported one notable detail - the pagination doesn't work because the page select is limited to 10k or so `options` natively by the browser. 

Two reasonable options I see:
1. Turn off page selection when the data set is huge
  - We can short circuit the logic in Pagination by setting `pageInputDisabled: true` and set `pageSize` to the same number of items/rows. With this, it should only put one `option` in the `select`.
2. Limit the select to the first 100 pages.
  - We could provide an affordance to the user that more pages exist by adding a 101th element with a value of `...` that would call a callback to allow the consuming application to handle it however they choose. Do nothing, pop a modal, pre-fill filters, show a toast notification etc.

**Comment by tay1orjones** [comment]
Carbon has an open item on this https://github.com/carbon-design-system/carbon/issues/4365

The currently open PR there will provide a refactored Pagination component that allows you to configure pagination to not have a page selection dropdown leaving the user with the sole option to move forwards/backwards. I think this is a good first step for large data sets with many many rows.

Beyond that, there is a separate issue to further enhance Pagination to use a number input instead of a select dropdown. https://github.com/carbon-design-system/carbon/issues/5546

In the meantime, we should limit the select to <10000 options as this is what's breaking the browser.
