### ISSUE TITLE
[Table]: Support internal vertical scrolling

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#55]
Our current Entity Type table supports internal vertical table scrolling

**Comment by scottdickerson** [comment]
this fell out of MVP

**Comment by tay1orjones** [comment]
Fixed/sticky header is now supported in the stock Carbon v10.4 DataTable

**Comment by davidicus** [comment]
@scottdickerson @lukefirth Does our table pattern that uses pagination allow for scrolling tables?

**Comment by lukefirth** [comment]
@davidicus apologies for the delay in getting to this.

The short answer is 'yes, but only in set circumstances'

That circumstance is where:
- The table row count at the defined row height = **X**
- The table is bound to a certain max height of **Y** due to needing to fit a set sized container (such as in the table card on the dashboard components).
- And **X** > **Y**

In other words, when the table is restricted to a certain height for some reason, and then asked to display more information than can fit in that height. Which is preferable to forcing the table to adopt a row count that satisfies the height it is restricted to (although we may use the height to determine a default row count - but that should be down to the given implementation I believe).

**Comment by lukefirth** [comment]
And it should be said that in normal circumstances, I believe it would be expected that the table is not in a fixed sized container, so increasing row count would make the table taller and make use of page wide scrolling.

**Comment by davidicus** [comment]
This issue is stale. Closing. Please re-open if needed.
