### ISSUE TITLE
[Card] Long titles in cards won't show on mobile device

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#639]
since the long titles are truncated using CSS only and only show their tooltips on Hover, they are not readable on a mobile device

**Comment by stuckless** [comment]
@scottdickerson  this pattern of "long text" and supporting mobile rendering is why in graphite we have a 'TextOverflow' component and we rarely render text on it's own.  For all values, labels, data, etc, everything is wrapped in a` <TextOverflow>` to allow us to uniformly handle what happen.  I'm not 100% happy with our implementation, but, the good news is that when/if we should redo it no downstream components need to be changed.

Manageing this is not trivial either, since, you need to check the post rendered element to detect the overflow and then hook in the popup controller to manage the click/show of the popup tooltip.  It also means that the labels need to listen for resize events on the page and check themselves as the screen changes size, etc.  But as I said, one pattern in one place.

Something to consider as you attempt this problem.

**Comment by bjornalm** [comment]
There is still the CSS solution for card titles, but now it is also possible to click on a truncated card title to get the Carbon Tooltip showing the full text.

![image](https://user-images.githubusercontent.com/5167091/76335310-9d5ecf00-62f4-11ea-83f8-02cbb22884c7.png)

**Comment by scottdickerson** [comment]
I think now that it's clickable this fixes the issue
