### ISSUE TITLE
[Dashboard]: Refactor the components to split the rendering and data awareness

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#653]
Need to better split the rendering responsibilities of the Dashboard and data fetching components so that @stuckless can reuse them in other products with different backends.

<sub>[Internal issue #89](https://github.ibm.com/Watson-IoT/pal-tracking/issues/89)</sub>

**Comment by scottdickerson** [comment]
Split out rendering Dashboard component from DataLoader component
CardRenderer splits the data state as well as the controls state and full card state
renderProp with the local card control state

How could the Maximo team reuse our value card from within their dashboards, could we allow a custom fetch function to be provided at the card level

Try getting the Value Card to work on Maximo Data from the Dashboard

Timeline December

**Comment by alronz** [comment]
@scottdickerson around this topic, I noticed that you moved the schema validation to the library level instead of the dashboard level. Would it be possible to allow some flexibility in the [dataSource](https://github.com/IBM/carbon-addons-iot-react/blob/master/src/utils/schemas/dashboardContent.json#L37) object to allow for customization? Currently in MWI dashboard we translate it differently to our backend. One example is that we support `orderBy`.  Also we might need other fields in the cards, for example we want to group some cards together, e.g: all KPI value cards will be called in a single API, etc..  
What are your thoughts about this?

**Comment by scottdickerson** [comment]
here's the external github link where the work will actually be done:
https://github.com/IBM/carbon-addons-iot-react/issues/653

**Comment by scottdickerson** [comment]
@alronz let's chat and make sure whatever we do here satisfies your usecase as well as @sls-ca

**Comment by scottdickerson** [comment]
@alronz just pushed a PR refactor, please take a look when you get a chance....
