### ISSUE TITLE
[Table] Provide example story on how to render custom component inside Table, figure out how to handle sort/search as well

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#76]

**Comment by scottdickerson** [comment]
sls@ca.ibm.com

**Comment by stuckless** [comment]
There are number of different things that need to happen here.

1. The `data` model that sent to the table for rendering, should just be data.  It should not be a mix of data + Nodes.  Putting aside the "religous" arguments of mixing data + UI Elements, there is a performance impact here.  If I load 100 items, then I need to create a React element for each cell, in each row.  [React Render Props](https://reactjs.org/docs/render-props.html) was created to solve this problem.   By using a render property, then the table configuration can support `cellRenderer` and a custom function can be provided.   During the render process of the cell, the, table's cell render function would be used and passed the row id, col id, row data, cell name, and the cell's value.   The Render function, can then determine how it should render that data, including, if it needs some i18n logic applied.  And it's lazily done at the time that it is rendered.

2. Row Details suffers from the same problem as cells, in that it is expected that the row details is pushed into the data model and created up front, before the table rendered, for all rows.  Again, a `render prop` would be preferred here, since, the creation of that details UI can be lazilly done and created dynamically using a render function.  Like the cell, the row details, would be passed information, like, row id, row data, items array.  The `rowDetails` render property can then constuct a row details dynamically based on the data passed in.

3. Sorting and Filtering would happen against the data in the data model and is only something that StatefulTable would use.  In this case, the sorting/filtering would simply sort the data as data (since it is not a mix of data + UI elements).   If you wanted to make it more flexible you possibly add a `sortValue` and `filterValue` call back functions to the StatefulTable so that it can be wired up to provde a function that can convert a data value into something sortable or filterable.  It would likely need the row, column name, and column value.

For 3, above, I purposely mentioned that sorting/filter should be on the StatefulTable, since, on a normal table that is fed a data model from a database, it's likely that the table itself will never actually sort or filter, but rather use the onSort onFilter callbacks and delegate to the server which returns a new data model.

Using render properties for the cells also enables things like inline table editing without the table needing to do anything to support it.  ie, an app developer can choose to use an input componet as the cell's rendere and wire it up so that changes are reflected in the data model.  The table never needs to know about it.
