### ISSUE TITLE
[PageWizard] Doesn't validate the current step if you leave it by clicking the Progress Indicator

### ISSUE THREAD

**Issue by scottdickerson** [IBM/carbon-addons-iot-react#877]
### Describe the bug

Even though I can't click Next to validate the current form page, because of this error, I am allowed to click the Progress Indicator and skip to the end.

Create a Step with validation rules, notice that even if they're failing, you can use Progress Indicator to skip steps forward.  Previous should be allowed, but clicking on future steps should be prevented if the current step is failing validation

![image](https://user-images.githubusercontent.com/6663002/73760217-aa573400-4732-11ea-8d63-19fbb661db77.png)

**Comment by smohtadi** [comment]
Hi, I would like to work on this issue. Is it still open?

**Comment by davidicus** [comment]
@smohtadi thanks for volunteering. Sorry for the delay in response. We are consolidating our issue management so we can more easily track and reply. 

This issue seems to still be open so please feel free to submit a PR for this fix. Thanks again.

**Comment by rawa-resul** [comment]
@scottdickerson I believe the issue is because the progress indicator and pagewizard step are decoupled from each other. There is currently no way of disabling the next step in the progress indicator. The way I have it in the new progress indicator is by default making it unclickable so that the entire flow goes through the PageWizrd. I will however point this out to @lukefirth and see what he says.
