### ISSUE TITLE
Dashboard within accordion rendering as a stack

### ISSUE THREAD

**Issue by davidicus** [IBM/carbon-addons-iot-react#939]
copied from PAL tracking [issue](https://github.ibm.com/Watson-IoT/pal-tracking/issues/259)

Occuring in APM  here: http://mahi-docker09.swg.usma.ibm.com:3000/#/assetDetail?ids=1588

The dashboard is automatically adjusting itself on the screen when rendering. 
1: The dashboard inside of the Predictions accordion (and any other accordion) do not properly render when opened.  On screen re-size, they "snap" into the proper position.

![stacking](https://media.github.ibm.com/user/17018/files/aae87c80-4e4e-11ea-9ba0-d8a8e20dbc33)

2: The dashboard causes a horizontal scroll on the screen. When you re-size the browser, the horizontal scroll disappears. 
![horizontal scroll](https://media.github.ibm.com/user/17018/files/36640c80-4e53-11ea-814a-0b98d8a87fe0)

**Comment by stuckless** [comment]
Here's a CRA that demonstrates the dashboard overflow issue.  In short this is caused because of page animations.  ie, we want to show a little bump when you navigate to the page.  The dashboard never updates itself based on available space so it overflows.  When you build this app, it starts on a main page, just click the dashboard on the side menu to show the dashboard view with an overflow.

[dashboard-overflow.zip](https://github.com/IBM/carbon-addons-iot-react/files/4232483/dashboard-overflow.zip)

**Comment by davidicus** [comment]
@stuckless that is what I needed. 

![image](https://user-images.githubusercontent.com/1590966/74978686-2b811d00-53fb-11ea-8b73-17ec76598258.png)

This should be applied to the container and it allows DashboardGid to calculate properly. The only other way is to force trigger a render but then you would lose the animation in.

**Comment by davidicus** [comment]
Closing issue since there is no component change. @stuckless please feel free to reopen if necessary.
