### ISSUE TITLE
What's the best approach to load fonts locally? 

### ISSUE THREAD

**Issue by ilovepumpkin** [IBM/carbon-addons-iot-react#992]
Our product needs to support onprem deployment and WebScan does not allow to load resources from external links, so we have to load all resources from our own deployment, including fonts. 

I see in carbon-addons-iot-react.css, the font urls are pointing to https://fonts.gstatic.com. And I looked at the source code - it seems that this font path is not configurable. So now I have to download all font files and manage them and replace all the font path to our local fonts path, and manage the font files and updated css file in our repo. The problem of this way is that if the font file name is changed (e.g. zYX7KVElMYYaJe8bpLHnCwDKhdTmvIRcdvfo.woff), our build is broken.  Certainly I could move the "download fonts" step into the build process, which ensures that I always get the latest font file names from the latest carbon iot react package css file. But I am not sure if it is worthy to make it so complicated.

Is there any better method to handle this situation?

**Comment by tay1orjones** [comment]
In order to configure this you'll need to be using the `.scss` files. There is no way to configure the pre-built `.css` file we provide.

When using the `.scss` this seems to be the general approach [based on this slack conversation](https://ibm-ai-apps.slack.com/archives/C2K6RFJ1G/p1575303196457200):

1. [Disable the `$css--font-face` global flag](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/sass.md#global-flags)
1. Self-host the files ([source here](https://github.com/IBM/plex)) and define the `@font-face` with your self-hosted files ([documentation here](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/ibm-plex.md#self-hosted)). 

[Here is some additional information on the `@font-face` rule in Carbon's documentation](https://github.com/carbon-design-system/carbon/blob/master/docs/guides/ibm-plex.md#font-face)

Note that global flags should work with our sass entrypoint, but [the path will be slightly different](https://github.com/IBM/carbon-addons-iot-react#styling):
```
$css--reset: false;
@import 'carbon-addons-iot-react/lib/scss/styles.scss';
```

**Comment by ilovepumpkin** [comment]
Okay, great! I will try this way. Thanks a lot!
